### ISSUE TITLE
New features plan

### ISSUE THREAD

**Issue by gregoryloichot** [solewniczak/dtable#11]
Hello, 

I appreciate your dtable plugin, and I have 2 questions about it.

First, do you know if the "all_tables" (turns all tables into dtables) options will be fixed ?
And, is it in your plans to add buttons on the Dokuwiki editor to create (and edit) dtables?

Thanks for your answer.

**Comment by hafron** [comment]
> I appreciate your dtable plugin, and I have 2 questions about it.
>
> First, do you know if the "all_tables" (turns all tables into
> dtables) options will be fixed ?
I hope it will be fixed one day, but currently I don't have time to do
it. You may try edittable plugin by Andreas Gohr. It allows to edit all
dokuwiki tables by default (although it works differently than dtable).

> And, is it in your plans to add buttons on the Dokuwiki editor to
> create (and edit) dtables?
Would you mean special button that will insert <dtable></dtable> tags in
your page source?

BR,
Szymon

**Comment by gregoryloichot** [comment]
> Would you mean special button that will insert <dtable></dtable> tags in
your page source?

Yes, something like this.

**Comment by hafron** [comment]
It should be quite easy ;) I will try to implement it in the nearest future.

**Comment by solewniczak** [comment]
Fixed by #12
